<h1 style='color:blue;' align='center'>K-Fold Cross Validation</h2>

The code is heavily borrowed from https://github.com/codebasics/py/blob/master/ML/12_KFold_Cross_Validation/12_k_fold.ipynb

#K-Fold crosss validation on dummy dataset

In [1]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [3]:
numbers = [i for i in range(1, 10)]
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
for train_idx, test_idx in kf.split(numbers):
    print(train_idx, test_idx)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn import datasets

In [6]:
iris = datasets.load_iris()

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.3)

**Logistic Regression**

In [8]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9555555555555556

**K-Nearest Neighbour Classifier**

In [9]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn.score(X_test, y_test)

0.9777777777777777

In [70]:
#Decision Tree

In [10]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt.score(X_test, y_test)

0.9555555555555556

**Random Forest**

In [11]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9555555555555556

<h2 style='color:purple'>KFold cross validation</h2>

**Use Startified K-Fold cross validation for  IRIS example**

In [12]:
def get_accuracy(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [13]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

accuracy_logr = []
accuracy_knn = []
accuracy_dt = []
accuracy_rf = []

for train_index, test_index in folds.split(iris.data,iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], \
                                       iris.target[train_index], iris.target[test_index]
    print(get_accuracy(LogisticRegression(), X_train, X_test, y_train, y_test))  
    print(get_accuracy(KNeighborsClassifier(), X_train, X_test, y_train, y_test))
    print(get_accuracy(DecisionTreeClassifier(),X_train, X_test, y_train, y_test))
    print(get_accuracy(RandomForestClassifier(), X_train, X_test, y_train, y_test))

E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.98
0.98
0.98
0.98
0.96
0.98
0.92
0.94
0.98
0.98
0.98
0.98


In [14]:
accuracy_logr

[]

In [15]:
accuracy_knn

[]

In [16]:
accuracy_dt

[]

In [17]:
accuracy_rf

[]

<h2 style='color:purple'>cross_val_score function</h2>

In [18]:
from sklearn.model_selection import cross_val_score

**Logistic regression model performance using cross_val_score**

In [20]:
cross_val_score(LogisticRegression(), iris.data, iris.target,cv=3)

E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

**svm model performance using cross_val_score**

In [21]:
cross_val_score(KNeighborsClassifier(), iris.data, iris.target,cv=3)

array([0.98, 0.98, 0.98])

**Decision Tree performance using cross_val_score**

In [24]:
cross_val_score(DecisionTreeClassifier(), iris.data, iris.target,cv=3)

array([0.98, 0.94, 0.96])

**random forest performance using cross_val_score**

In [25]:
cross_val_score(RandomForestClassifier(n_estimators=40),iris.data, iris.target,cv=3)

array([0.98, 0.94, 0.98])

cross_val_score uses stratifield k-fold by default

<h2 style='color:purple'>Exercise</h2>

Use Breast cancer dataset from sklearn library (https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html#sklearn.datasets.load_breast_cancer) and use cross_val_score against following
models to measure the performance of each. In the end figure out the model with best performance,
1. Logistic Regression
2. KNN
3. Decision Tree
4. Random Forest